---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings
title: Skyline Lab 
startUrl: https://homepage.skyline-lab.com

background:
  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 50 # 0-100


layout:
  # Server Tools:
  #   icon: https://cdn-icons-png.flaticon.com/512/252/252035.png

  # Bookmark Group on First Tab:
  #   tab: First

  Servers:
    tab: Servers
    style: row
    columns: 4

  Services:
    tab: Services
    columns: 4

  Storage:
    tab: Storage
    style: columns
    columns: 2

  # Bookmark Group on Fourth Tab:
  #   tab: Fourth

  # Service Group on every Tab:
  #   style: row
  #   columns: 4


providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey


